name: Build Whitepaper
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: whitepaper
          path: main.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        tag_name: v1.0.0
        with:
          files: main.pdf