name: Build Whitepaper
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Rename
        run:  mv main.pdf taiko-whitepaper.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: taiko-whitepaper.pdf

      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@master
        with:
          path: ./taiko-whitepaper.pdf
        service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}
